### ISSUE TITLE
Sync issues with community policies

### ISSUE THREAD

**Issue by maxime-roy** [JulianHayward/AzAdvertizer#10]
**Describe the bug**
Hi! 

I think there might be an issue with the synchronization of the community policies. From AzAdvertizer, I'm not able to see the policy 4f8668bc-8adc-44fc-b6e1-20cf37dc6738, but it's available [here](https://github.com/Azure/Community-Policy/blob/main/policyDefinitions/Tags/required-tag-and-value-set-on-resource-groups/azurepolicy.jsonc) on the main branch . 

Thanks !

**Comment by JulianHayward** [comment]
ho!

good catch and thanks for reporting.

Checked and found three not synced policies, due to that the files are `.jsonc` whilst the syncer looks for `.json` (actually `azurepolicy.json`)

* https://github.com/Azure/Community-Policy/tree/main/policyDefinitions/Tags/required-tag-and-value-set-on-subscriptions
* https://github.com/Azure/Community-Policy/tree/main/policyDefinitions/Tags/required-tag-and-value-set-on-resource-groups
* https://github.com/Azure/Community-Policy/tree/main/policyDefinitions/Tags/required-tag-and-value-set-on-resources

There seem no comments in the files at all, so changing the file extensions should be straight forward.
Would you be willing to raise the PRs against the community repo?

**Comment by maxime-roy** [comment]
Will do! 

Maybe at some point the syncer could support jsonc by stripping the comments before "ingesting it " ?

**Comment by DFRZ7** [comment]
@maxime-roy @JulianHayward Hi, we have presented a PR for this. Should be accepted in a couple of days. Thank you.
https://github.com/Azure/Community-Policy/pull/452
