### ISSUE TITLE
CSV option for All Resource Provider Operations

### ISSUE THREAD

**Issue by jwgarrett** [JulianHayward/AzAdvertizer#7]
I would like the option to download a CSV with all of the current columns in the html view as a comma and/or semicolon CSV please. Awesome work :-)

https://www.azadvertizer.net/azresourceoperationadvertizer_all.html

**Comment by jwgarrett** [comment]
This would be a full download including all of the values for usedByRole, notusedByRole, usedbyPolicy, usedbyPolicySet. It looks like you can enable export via aggrid too https://www.ag-grid.com/javascript-data-grid/excel-export/ and the community csv export is here https://www.npmjs.com/package/@ag-grid-community/csv-export
@JulianHayward I could really use this feature as soon as possible. I am hoping it is a quick fix. 👍

**Comment by JulianHayward** [comment]
@jwgarrett 
the actual data is optimized, so that traffic/files do not get too big.. 
This is what resProvOps raw data actually looks like https://www.azadvertizer.net/resProvOps.json what you are seeing on the site is rendered (cell renderer) data.

_The raw values, and not the result of cell renderer will get used_
ref: https://www.ag-grid.com/react-data-grid/csv-export/#what-gets-exported

So export using the AG-Grid capability is not an option but may consider providing a csv for download. And yet again, please provide a use case :) / how is it adding value for YOUR scenario? Please draw that scenario.

**Comment by jwgarrett** [comment]
The scenario allows custom personas to be created for our business purpose which have one or more azure built-in roles assigned. The next step would be to have them roll up to the categories such as DevOps, Migration, and Monitor. After that I would identify reader, user, and admin personas for each of the resource provider categories based upon the operation and kind. If the categories were present along with the usedByRole to define the least privileged role necessary by resource provider category. The data that is missing is if the operation is considered privileged or not. I hope this helps paint the picture and thanks for the help on your side.

**Comment by JulianHayward** [comment]
backlogged
